# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-07 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=None, max_length=500)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('password', models.CharField(max_length=500)),
                ('name', models.CharField(default=None, max_length=500)),
            ],
        ),
    ]
